// ─────────────────────────────────────────────
//  Mock product data — used when Firebase is
//  not yet configured (demo mode)
// ─────────────────────────────────────────────
export const MOCK_PRODUCTS = [
  {
    id: 'mock-1',
    name: 'Ivory Linen Blazer',
    price: 45000,
    category: 'Corporate Wear',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
    description: 'Impeccably tailored ivory linen blazer. Structured shoulders, relaxed fit. The boardroom reimagined.',
    featured: true,
  },
  {
    id: 'mock-2',
    name: 'Vintage Washed Tee',
    price: 12500,
    category: 'Vintage Shirts',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    description: 'Sun-faded, perfectly worn. Every crease tells a story. Oversized silhouette, vintage soul.',
    featured: true,
  },
  {
    id: 'mock-3',
    name: 'Cream Essential Sweatshirt',
    price: 18500,
    category: 'Sweatshirts',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
    description: 'Heavyweight 400gsm fleece in natural cream. Dropped shoulders, raw hem. Comfort as luxury.',
    featured: true,
  },
  {
    id: 'mock-4',
    name: 'Oud & Amber Atomizer',
    price: 8500,
    category: 'Perfume Atomizers',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80',
    description: 'Travel-sized luxury. Deep oud accord with warm amber base. 10ml refillable brass atomizer.',
    featured: true,
  },
  {
    id: 'mock-5',
    name: 'Linen Throw Pillow Set',
    price: 15000,
    category: 'Room Decor',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    description: 'Set of two washed linen cushion covers in natural sand. Hidden zip, inner included.',
    featured: false,
  },
  {
    id: 'mock-6',
    name: 'Tonka Scented Candle',
    price: 9800,
    category: 'Scented Candles',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80',
    description: 'Pure soy wax, wooden wick. 50hr burn time. Tonka bean, vanilla, sandalwood. Hand-poured.',
    featured: true,
  },
  {
    id: 'mock-7',
    name: 'Sculptural Bud Vase',
    price: 11200,
    category: 'Fancy Bottles',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
    description: 'Hand-thrown stoneware in warm terracotta glaze. Organic form, singular aesthetic.',
    featured: false,
  },
  {
    id: 'mock-8',
    name: 'Minimal Leather Card Holder',
    price: 7500,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    description: 'Full-grain tan leather. Holds 4 cards. Ages beautifully. The only one you will ever need.',
    featured: false,
  },
  {
    id: 'mock-9',
    name: 'Silk Cargo Trousers',
    price: 32000,
    category: 'Aesthetic Items',
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=600&q=80',
    description: 'Fluid silk-blend cargo trousers. Functional meets ethereal. Wide leg, mid-rise.',
    featured: true,
  },
  {
    id: 'mock-10',
    name: 'Pebbled Leather Tote',
    price: 28000,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80',
    description: 'Unstructured pebbled leather tote in cognac. Magnetic closure, internal zip pocket.',
    featured: false,
  },
  {
    id: 'mock-11',
    name: 'Oversized Graphic Sweatshirt',
    price: 21000,
    category: 'Sweatshirts',
    image: 'https://images.unsplash.com/photo-1572495532056-8583a9686c04?w=600&q=80',
    description: 'Brushed cotton fleece with minimal tonal graphic. Boxy fit, ribbed trims.',
    featured: false,
  },
  {
    id: 'mock-12',
    name: 'Rattan Desk Organiser',
    price: 13500,
    category: 'Room Decor',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
    description: 'Handwoven rattan desk organiser. Three compartments. Pairs with any aesthetic.',
    featured: false,
  },
];

export const CATEGORIES = [
  { name: 'Aesthetic Items', emoji: '✦', description: 'Curated pieces that define your aesthetic' },
  { name: 'Corporate Wear', emoji: '◈', description: 'Luxury suiting for the modern professional' },
  { name: 'Sweatshirts', emoji: '○', description: 'Premium fleece. Comfort without compromise' },
  { name: 'Vintage Shirts', emoji: '◇', description: 'Perfectly worn, endlessly wearable' },
  { name: 'Room Decor', emoji: '□', description: 'Objects that elevate your space' },
  { name: 'Perfume Atomizers', emoji: '◉', description: 'Signature scents, portable luxury' },
  { name: 'Scented Candles', emoji: '△', description: 'Ambiance in every flame' },
  { name: 'Fancy Bottles', emoji: '◑', description: 'Sculptural vessels for your vanity' },
  { name: 'Accessories', emoji: '✧', description: 'The finishing detail' },
];
